quarkus:
  http:
    host: 0.0.0.0
    port: ${HTTP_PORT:8080}
  hibernate-orm:
    dialect: "org.hibernate.dialect.PostgreSQLDialect"
    database:
      generation: none
    multitenant: DATABASE
---
"%dev":
  quarkus:
    http:
      port: 4445
    hibernate-orm:
      multitenant: DATABASE
    datasource:
      "base":
        devservices:
          enabled: true
          db-name: base
        db-kind: postgresql
      "mycompany":
        db-kind: postgresql
        devservices:
          enabled: true
          db-name: mycompany

    flyway:
      "base":
        migrate-at-start: true
        locations: [ classpath:db/migration ]
      "mycompany":
        migrate-at-start: true
        locations: [ classpath:db/mycompany ]
---
"%prod":
  quarkus:
    http:
      port: ${HTTP_PORT:8080}
