quarkus:
  http:
    host: 0.0.0.0
    port: ${HTTP_PORT:8080}
  hibernate-orm:
    database:
      generation: none
    multitenant: DISCRIMINATOR

  datasource:
    db-kind: postgresql
---
"%dev":
  quarkus:
    http:
      port: 4445
---
"%prod":
  quarkus:
    http:
      port: ${HTTP_PORT:8080}
