quarkus:
  http:
    host: 0.0.0.0
    port: ${HTTP_PORT:8080}
  hibernate-orm:
    dialect: "org.hibernate.dialect.PostgreSQLDialect"
    database:
      generation: none
    multitenant: SCHEMA

  datasource:
    db-kind: postgresql

  flyway:
    schemas: public,base,mycompany
    migrate-at-start: true
---
"%dev":
  quarkus:
    http:
      port: 4445
    hibernate-orm:
      multitenant: SCHEMA
---
"%prod":
  quarkus:
    http:
      port: ${HTTP_PORT:8080}
